import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { ASSETS } from "./AssetRegistry.js";

export class World{
  constructor(T,R){this.T=T;this.R=R;this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(62,innerWidth/innerHeight,.1,1200);this.renderer=new T.WebGLRenderer({canvas:document.querySelector("#game"),antialias:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.shadowMap.enabled=true;this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=T.SRGBColorSpace;this.world=new R.World({x:0,y:-18,z:0});addEventListener("resize",()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)})}
  build(){const T=this.T,s=this.scene;s.background=new T.Color(0x8aa6bd);s.fog=new T.Fog(0x8aa6bd,130,520);s.add(new T.HemisphereLight(0xcfe4ff,0x334455,2.2));const sun=new T.DirectionalLight(0xffe5bf,3);sun.position.set(120,180,80);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);s.add(sun);const ground=new T.Mesh(new T.PlaneGeometry(1000,1000),new T.MeshStandardMaterial({color:0x252b2f,roughness:.92}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;s.add(ground);this.world.createCollider(this.R.ColliderDesc.cuboid(500,.05,500),this.world.createRigidBody(this.R.RigidBodyDesc.fixed().setTranslation(0,-.05,0)));const roadMat=new T.MeshStandardMaterial({color:0x111417,roughness:.8}),road=new T.Mesh(new T.PlaneGeometry(520,24),roadMat);road.rotation.x=-Math.PI/2;road.position.y=.01;s.add(road);const road2=road.clone();road2.rotation.z=Math.PI/2;s.add(road2);for(let i=-5;i<=5;i++)for(let j=-5;j<=5;j++)if(Math.abs(i)>1&&Math.abs(j)>1)this.buildBlock(i*48,j*48);this.loadFreeCity()}
  buildBlock(x,z){const T=this.T,h=8+Math.random()*35,w=18+Math.random()*16,d=18+Math.random()*16,m=new T.MeshStandardMaterial({color:new T.Color().setHSL(.58,.08,.18+Math.random()*.12),roughness:.8}),b=new T.Mesh(new T.BoxGeometry(w,h,d),m);b.position.set(x+(Math.random()-.5)*10,h/2,z+(Math.random()-.5)*10);b.castShadow=true;b.receiveShadow=true;this.scene.add(b);const rb=this.world.createRigidBody(this.R.RigidBodyDesc.fixed().setTranslation(b.position.x,b.position.y,b.position.z));this.world.createCollider(this.R.ColliderDesc.cuboid(w/2,h/2,d/2),rb)}
  async loadFreeCity(){try{const loader=new GLTFLoader(),gltf=await loader.loadAsync(ASSETS.house),base=gltf.scene;for(let i=0;i<12;i++){const m=base.clone(true);m.position.set((i%4-1.5)*52,0,(Math.floor(i/4)-1)*52);m.scale.setScalar(2.4);m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});this.scene.add(m)}const rock=await loader.loadAsync(ASSETS.rock);for(let i=0;i<20;i++){const r=rock.scene.clone(true);r.position.set((Math.random()-.5)*220,0,(Math.random()-.5)*220);r.scale.setScalar(.8+Math.random()*1.6);this.scene.add(r)}}catch(e){console.warn("CC0 city assets unavailable; procedural world remains active",e)}}
  update(){this.world.step()}render(){this.renderer.render(this.scene,this.camera)}
}