export type Actions={moveX:number;moveY:number;lookX:number;lookY:number;sprint:boolean;jump:boolean;crouch:boolean;roll:boolean;interact:boolean};
const clamp=(v:number)=>Math.max(-1,Math.min(1,v));
export class InputSystem{
 readonly actions:Actions={moveX:0,moveY:0,lookX:0,lookY:0,sprint:false,jump:false,crouch:false,roll:false,interact:false}; private keys=new Set<string>(); private just=new Set<string>(); private pointers=new Map<number,{kind:"move"|"look";x:number;y:number}>();
 constructor(private canvas:HTMLCanvasElement){
 addEventListener("keydown",e=>{if(!this.keys.has(e.code))this.just.add(e.code);this.keys.add(e.code);if(e.code==="Space")e.preventDefault()},{passive:false}); addEventListener("keyup",e=>this.keys.delete(e.code)); addEventListener("blur",()=>this.reset()); addEventListener("visibilitychange",()=>document.hidden&&this.reset());
 const map:Record<string,string>={jump:"Space",crouch:"ControlLeft",run:"ShiftLeft",interact:"KeyE"}; document.querySelectorAll<HTMLElement>("[data-action]").forEach(el=>{const c=map[el.dataset.action||""];if(!c)return;const down=(e:PointerEvent)=>{e.preventDefault();this.keys.add(c);this.just.add(c);el.setPointerCapture?.(e.pointerId)};const up=()=>this.keys.delete(c);el.addEventListener("pointerdown",down);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up);el.addEventListener("lostpointercapture",up)});
 this.bindStick("#move","move");this.bindStick("#look","look"); canvas.addEventListener("click",()=>matchMedia("(pointer:fine)").matches&&canvas.requestPointerLock?.()); addEventListener("mousemove",e=>{if(document.pointerLockElement===canvas){this.actions.lookX+=e.movementX*.0022;this.actions.lookY+=e.movementY*.0018}});
 }
 private bindStick(selector:string,kind:"move"|"look"){const el=document.querySelector<HTMLElement>(selector);if(!el)return;el.style.touchAction="none";el.addEventListener("pointerdown",e=>{if(this.pointers.size)return;e.preventDefault();this.pointers.set(e.pointerId,{kind,x:e.clientX,y:e.clientY});el.setPointerCapture?.(e.pointerId)});el.addEventListener("pointermove",e=>{const p=this.pointers.get(e.pointerId);if(!p)return;const r=Math.max(45,Math.min(el.clientWidth,el.clientHeight)*.32);if(kind==="move"){this.actions.moveX=clamp((e.clientX-p.x)/r);this.actions.moveY=clamp((e.clientY-p.y)/r)}else{this.actions.lookX+=(e.clientX-p.x)*.0005;this.actions.lookY+=(e.clientY-p.y)*.0005;p.x=e.clientX;p.y=e.clientY}},{passive:false});const end=(e:PointerEvent)=>{if(!this.pointers.delete(e.pointerId))return;if(kind==="move"){this.actions.moveX=0;this.actions.moveY=0}else{this.actions.lookX=0;this.actions.lookY=0}};el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end);el.addEventListener("lostpointercapture",end)}
 down(c:string){return this.keys.has(c)} pressed(c:string){const v=this.just.has(c);this.just.delete(c);return v} sample(){this.actions.moveX=clamp(this.actions.moveX+(this.down("KeyD")?1:0)-(this.down("KeyA")?1:0));this.actions.moveY=clamp(this.actions.moveY+(this.down("KeyS")?1:0)-(this.down("KeyW")?1:0));this.actions.sprint=this.down("ShiftLeft")||this.down("ShiftRight");this.actions.crouch=this.down("ControlLeft")||this.down("ControlRight");this.actions.jump=this.pressed("Space");this.actions.roll=this.pressed("KeyQ");this.actions.interact=this.pressed("KeyE");return this.actions} endFrame(){this.just.clear();this.actions.lookX=0;this.actions.lookY=0} reset(){this.keys.clear();this.just.clear();this.pointers.clear();Object.assign(this.actions,{moveX:0,moveY:0,lookX:0,lookY:0,sprint:false,jump:false,crouch:false,roll:false,interact:false})}}
